name: Poetry Check
on: pull_request

env:
  PYTHON_VERSION: "3.13"
  POETRY_VERSION: "2.0.1"
  POETRY_URL: https://install.python-poetry.org

jobs:
  poetry-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Run image
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: ${{ env.POETRY_VERSION }}
      - name: Run poetry check
        run: poetry check